theme: jekyll-theme-slate
title: The Personal Page of James Noble
description: Contains various information about myself: academic research interests, personal interests, and any other relevant details. 
plugins:
 - jemoji
url:  "https://realjamesnoble.github.io/"
markdown: kramdown
